# Dockerfile
FROM pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime

WORKDIR /app

COPY app/ /app/

# Instala dependencias del proyecto
RUN pip install --no-cache-dir -r requirements.txt
#Copia el resto del proyecto al contenedor
COPY . .       
# Expone el puerto que usa Streamlit
EXPOSE 8501

# Ejecuta la app con Streamlit
CMD ["streamlit", "run", "web.py", "--server.port=8501", "--server.enableCORS=false"]
