# Dockerfile.cpu
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./

# Instala dependencias generales y la versión CPU de torch explícitamente
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install torch==2.2.0+cpu --index-url https://download.pytorch.org/whl/cpu

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "app/web.py", "--server.port=8501", "--server.enableCORS=false"]
